apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiconsume
  namespace: mspoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiconsume
  template:
    metadata:
      labels:
        app: apiconsume
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: apiconsume
        image: satyendrasahu2021/apiconsume
        env:
        - name: APIURL
          value: secret-sync@azurekeyvault
        ports:
        - containerPort: 80
          name: apiconsume
---
apiVersion: v1
kind: Service
metadata:
  name: apiconsume
  namespace: mspoc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apiconsume

